### ISSUE TITLE
Default Pooling Method

### ISSUE THREAD

**Issue by bryanwong17** [WonderLandxD/WiKG#5]
Hi, thank you for the great work! I wonder which pooling method used as the final version of the model? Is it `mean` or `attn`? Thank you!

**Comment by WonderLandxD** [comment]
Hello, we use `mean` pooling as the final choice. In our experiments, we found that attention pooling also has competitive results, and you can explore the capability of different pooling strategies for your custom tasks.

**Comment by bryanwong17** [comment]
Got it, thanks!
